[global.databases.tweeter]
url = "postgres://tweeter:tweeter@localhost:5432/tweeter"

[development]
address = "localhost"
port = 8000
workers = 4
keep_alive = 5
log = "normal"
secret_key = "very secret"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5
log = "normal"
secret_key = "very secret"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5
log = "critical"
secret_key = "very secret"
limits = { forms = 32768 }